# Generated by Django 4.2.5 on 2023-10-02 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="alias",
        ),
    ]
