# Generated by Django 4.2.5 on 2023-10-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0002_rename_user_userprofile_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=140)),
                ("createt_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="Alias",
        ),
    ]
