# Generated by Django 4.2.5 on 2023-10-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0003_tweet_rename_userprofile_alias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="tweet",
            old_name="createt_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inicio.alias",
            ),
        ),
    ]
