# Generated by Django 4.2.5 on 2023-10-15 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0004_alter_tweet_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tweet",
        ),
    ]
