# Generated by Django 4.2.5 on 2023-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tweets/images/"),
        ),
    ]
