# Generated by Django 4.2.5 on 2023-10-17 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0002_tweet_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likers",
            field=models.ManyToManyField(
                blank=True, related_name="liked_tweets", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tweet",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
